a=4
b=6.6
c="string"
d=['ritik',"shikhar"]
e=('ritik','Shikar')
f={"Ritik","Shikhar"}
g={"Ritik":"Shikhar",25:42}
print(type(a))
print(type(b))
print(type(c))
print(type(d))
print(type(e))
print(type(f))
print(type(g))